### PR TITLE
Update to 1.15.2

### PR DESCRIPTION
**Pull request by PaintNinja**

### CODE REVIEW

**Comment by zlepper** [comment]
Hey, thank you for the PR :)

Is there a particular reason for the things labeled "coremod"? I'm not up to date on forge at all, so maybe just a link?

**Comment by PaintNinja** [comment]
https://github.com/MinecraftForge/CoreMods

Basically the func_230148_b_() doesn't have proper mappings so the coremod stuff fixes that. :)

**Comment by zlepper** [comment]
Alright, I have uploaded a build to curseforge now, thank you again for the PR :)

**Comment by PaintNinja** [comment]
No worries! Btw, if you want to credit me on curseforge as a maintainer or whatever, my username there is Paint_Ninja. If not, no problem.

**Pull request merged**
